author: "My Name"

title: "My title"

description: "My presentation"

# To override the location of RevealJS
#revealjs: "/my/custom/folder/" 

# List of slide files
# NOTE: forbidden keys: index.html (it is the output)
slides:
 - "slide1.html"
 - "slide2.html"
 - "slide3.html"
 - "slide4.html"
 - "thanks.html"

template:
 - "template.mustache"

# Templates in the slides
# NOTE: forbidden keys: author, title, description, inline, revealjs
view:
 templating: "Mustache templates"

inline:
 logo: "logo.svg"

