#!/usr/bin/env node
var fs = require('fs');
var YAML = require('yamljs');
var mustache = require('mustache');
var watch = require('glob-watcher');


var paths = {
  //presentation: "./example/"
  presentation: process.cwd()+'/'
}

var build = function() {
    var config = YAML.load(paths.presentation+'config.yml'),
        slides = config.slides.map(function(x) {
            // Ignore slides if the file has issues
            try {
                return fs.readFileSync(paths.presentation+x, {'encoding': 'utf8'});
            } catch (err) {
                console.log(err);
                return '';
            }
        }).join('\n\n'),
        template = fs.readFileSync(paths.presentation+'template.mustache', {'encoding': 'utf8'}),
        view = {
            revealjs: config.revealjs || __dirname+'/node_modules/reveal.js/',
            title: config.title || 'Title',
            author: config.author || 'Author',
            description: config.description || 'Description',
            inline: {}
        },
        partials = {
            slides: slides
        },
        output = config.output || 'index.html';

    // Add templates
    if (config.hasOwnProperty('templates'))
        for (var prop in config.templates)
            if (config.templates.hasOwnProperty(prop))
                view[prop] = config.templates[prop]

    // Add inline files
    if (config.hasOwnProperty('inline'))
        for (var prop in config.inline)
            if (config.inline.hasOwnProperty(prop))
                view.inline[prop] = fs.readFileSync(paths.presentation+config.inline[prop], {'encoding': 'utf8'});

    // Output file
    if (!config.hasOwnProperty('output'))
        config.output = 'index.html'

    var rendered = mustache.render(template, view, partials);
    
    fs.writeFileSync(paths.presentation+config.output, rendered ,{'encoding': 'utf8'});
    console.log("Written file: "+paths.presentation+'index.html');
};

// Initial call
build();

// Watcher
var watcher = watch([paths.presentation+'*', '!'+paths.presentation+'index.html']);
watcher.on('change', function(evt) {
    console.log(evt);
    build();
});
